---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---


```{r}


library(rvest) 

allframe = data.frame(Title=character(),
                 Author=character(), 
                 PushNum=character()) 

for(i in 2550:2581)
{
    PPTURL = paste0("https://www.ptt.cc/bbs/Tech_Job/index",i,".html")
    PPTContent = read_html(PPTURL)
    author = html_text(html_nodes(PPTContent,".author"))
    title = html_text(html_nodes(PPTContent,".title"))
    title = gsub("\n",replacement="",title) 
    title = gsub("\t",replacement="",title) 
    nrec = html_text(html_nodes(PPTContent,".nrec"))
    PPTframe = data.frame(Title = title
          ,Author = author
          ,PushNum = nrec)
    allframe = rbind(allframe,PPTframe)
}





```

## 爬蟲結果呈現
```{r}

knitr::kable(
    allframe[c("Title","Author","PushNum")])
```

## 解釋爬蟲結果 
```{r}
#三個欄位分別是主題，作者，推文數
str(allframe)
#總共抓了636個主題
```

解釋解釋解釋解釋

```{r}
#這是R Code Chunk
sort(table(allframe$Author),decreasing=TRUE)[1:10]
#發最多文的作者:由大到小排列發現匿名人士最多，wer11次之......
#有趣現象:暱稱W開頭的貌似都很愛發文
```

解釋解釋解釋解釋

人工結論與解釋解釋解釋解釋解釋解釋解釋
